name: svlint
version: &version v0.3.1
summary: SystemVerilog linter
description: |
  A lint checker supporting SystemVerilog ( IEEE Std. 1800-2017 )
base: core18
license: MIT

confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf

apps:
  svlint:
    command: svlint

parts:
  svlint:
    source: https://github.com/dalance/svlint.git
    source-tag: *version
    plugin: rust
    stage-packages:
      - libc6
      - libgcc1
      - libstdc++6
      - zlib1g
